
FROM python:3.9

WORKDIR /app

# Copy the requirements file to the working directory
COPY requirements.txt .

# Install the required Python dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the entire project to the working directory
COPY . .

# Set environment variables
ENV DJANGO_SETTINGS_MODULE=sap.settings
ENV PYTHONUNBUFFERED=1

# Expose port 8000 for the Django application
EXPOSE 8000

CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
