# Use the official Python image as the base image
FROM python:3.9

# Set the working directory inside the container
WORKDIR /app

# Set environment variables for SAPNWRFC_HOME, lib, and bin paths
ENV SAPNWRFC_HOME=/sap/nwrfcsdk
ENV LD_LIBRARY_PATH=$SAPNWRFC_HOME/lib
ENV PATH=$SAPNWRFC_HOME/bin:$PATH

# Copy the nwrfcsdk folder to the /sap/nwrfcsdk directory in the container
COPY nwrfcsdk $SAPNWRFC_HOME

# Copy the requirements file to the working directory
COPY requirements.txt .

# Install the required Python dependencies
RUN pip install -r requirements.txt

# Copy the entire project to the working directory
COPY . .

# Set environment variables for Django
ENV DJANGO_SETTINGS_MODULE=sap.settings
ENV PYTHONUNBUFFERED=1

# Install Redis server
RUN apt-get update && apt-get install -y redis-server

# Expose port 8000 for the Django application
EXPOSE 8000

# Install Flower for Celery monitoring
RUN pip install flower

# Start Redis server
CMD ["redis-server"]

# In another terminal, run Celery worker and Flower
CMD ["celery", "-A", "sap", "worker", "--loglevel=info"]
CMD ["flower", "--app=sap", "--broker=redis://localhost:6379/0"]

# Run the Django development server
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]

#docker build -t sap .
#docker run -p 8000:8000 sap