# Generated by Django 4.1.7 on 2023-04-26 16:09

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SAPConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ASHOST', models.CharField(max_length=255)),
                ('CLIENT', models.CharField(max_length=255)),
                ('SYSNR', models.CharField(max_length=255)),
                ('USER', models.CharField(max_length=255)),
                ('PASSWD', models.CharField(max_length=255)),
                ('saprouter', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SapDownloading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('downloading_id', models.UUIDField(default=app.models.get_unique_id)),
                ('status', models.CharField(choices=[('InProgress', 'InProgress'), ('Completed', 'Completed'), ('Error', 'Error')], default='InProgress', max_length=255)),
                ('total_rows', models.IntegerField(default=0)),
                ('fetched_rows', models.IntegerField(default=0)),
                ('table_name', models.CharField(max_length=255)),
                ('number_of_column', models.IntegerField(default=0)),
            ],
        ),
    ]
