# Generated by Django 4.1.7 on 2023-04-27 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sapdownloading',
            name='fetched_cols',
            field=models.IntegerField(default=0),
        ),
    ]
