# Generated by Django 4.1.7 on 2023-05-28 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_sapconfig_django_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='sapdownloading',
            name='error_message',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sapdownloading',
            name='sap_connection_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sapdownloading',
            name='success_message',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sapdownloading',
            name='status',
            field=models.CharField(choices=[('InProgress', 'InProgress'), ('validate', 'validate'), ('Completed', 'Completed'), ('Error', 'Error')], default='InProgress', max_length=255),
        ),
    ]
