# Generated by Django 4.1.7 on 2023-05-28 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_sapdownloading_file_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='sapdownloading',
            name='connection_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sapdownloading',
            name='is_stopped',
            field=models.BooleanField(default=False),
        ),
    ]
