# Generated by Django 4.1.7 on 2023-06-02 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_sapdownloading_connection_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileExtentions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Plain File', max_length=30, unique=True)),
                ('extension', models.CharField(default='txt', max_length=30)),
                ('separator', models.CharField(default='|', max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='sapdownloading',
            name='file_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.fileextentions'),
        ),
    ]
