# Generated by Django 4.1.7 on 2023-06-02 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_fileextentions_sapdownloading_file_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='sapdownloading',
            name='total_time',
            field=models.FloatField(default=0),
        ),
    ]
